version: 2
updates:
<<<<<<< HEAD
  - package-ecosystem: "npm" # See documentation for possible values
    directories: 
          - "/frontend"
          - "/backend" # Location of package manifests
=======
  # Enable version updates for pip (Python backend)
  - package-ecosystem: "pip"
    directory: "/backend"
>>>>>>> c515fc0da78e2790b6debafc683da566dcb353b4
    schedule:
      interval: "daily"
      time: "00:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "pip"
      include: "scope"

  # Enable version updates for npm (JavaScript/TypeScript frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "00:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "npm"
      include: "scope"
